language: node_js

node_js:
  - 10

cache:
  directories:
  - $HOME/.npm

services:
  - docker

script:
  - npm run test:ci -- -r lcov

after_success:
  - npm run upload

notifications:
  email: false
