name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: npm i
      - run: npm run test:ci -- -r lcov
      - run: CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} npm run upload
